name: Daily Update

on: 
  workflow_dispatch: # This allows manual execution of the workflow.
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC.

jobs:
  update: # This is the main job
    runs-on: ubuntu-latest # Ubuntu is generally faster and more cost-efficient for GitHub to run, making it the default choice. For most projects, Linux (Ubuntu) will work just fine even if developed on macOS.

    steps:
      # Step 1: Download the GitHub repository’s source code to the runner (the virtual machine where the action is being executed). Without this step, the subsequent steps wouldn't have access to the repository's code.
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Clone PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'artainmo'
          repository: 'Obsidian'
          access-token: ${{ secrets.PRIVATE_REPO_ACCESS }}
    
      - name: Update the obsidian repo.
        env: 
          API_GITHUB: ${{ secrets.API_GITHUB }}
        run: |
          python main.py
          cd Obsidian/Obsidian
          git config --local user.name "Arthur Tainmont"
          git config --local user.email "tainmontarthur@icloud.com"
          git add *
          git commit -m "automatic github_to_obsidian synchronization"
          git push

  keepalive-job: # This job's sole goal is to prevent the workflow from disabling after 60 days of inactivity
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@2.0.10
